version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: development
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"